<a href="https://colab.research.google.com/github/gnikita-pro/Stock-Sentiment-Analysis-from-News-Headlines/blob/main/STOCK_SHARE_PREDICTOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


# New Section

In [ ]:
#importing necessary modules
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.mixture import GaussianMixture as GMM
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')
!pip install streamlit
!pip install pyngrok

import streamlit as st
import pickle
import nltk
import string
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')



from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 9.2 MB 5.2 MB/s 
     |████████████████████████████████| 4.7 MB 39.8 MB/s 
     |████████████████████████████████| 78 kB 6.9 MB/s 
     |████████████████████████████████| 237 kB 79.1 MB/s 
     |████████████████████████████████| 164 kB 64.6 MB/s 
     |████████████████████████████████| 182 kB 76.0 MB/s 
     |████████████████████████████████| 62 kB 1.2 MB/s 
     |████████████████████████████████| 51 kB 7.4 MB/s 
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19581 sha256=7d006845b418ff85da2c24700b9587caf5f242653a315eadae44324d1b9cd071
  Stored in directory: /root/.cache/pip/wheels/19/09/72/3eb74d236bb48bd0f3c6c3c83e4e0c5bbfcbcad7c6c3539db8
Successfully built validators
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 761 kB 5.

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [ ]:
#reading csv file
df=pd.read_csv("/content/drive/MyDrive/ds3_project/Stock Headlines.csv", encoding= 'unicode_escape')

In [ ]:
#dropping NULL values in dataset
Noe=df.isnull().sum()
print("NULL values in each attribute before dropping",Noe)
df = df.dropna(axis=0)

Noe=df.isnull().sum()
print("NULL values in each attribute after dropping",Noe)




NULL values in each attribute before dropping Date       0
Label     48
Top1      52
Top2      60
Top3      70
Top4      93
Top5     104
Top6     111
Top7     118
Top8     127
Top9     135
Top10    144
Top11    156
Top12    162
Top13    171
Top14    179
Top15    187
Top16    191
Top17    198
Top18    208
Top19    213
Top20    222
Top21    232
Top22    246
Top23    252
Top24    256
Top25    258
dtype: int64
NULL values in each attribute after dropping Date     0
Label    0
Top1     0
Top2     0
Top3     0
Top4     0
Top5     0
Top6     0
Top7     0
Top8     0
Top9     0
Top10    0
Top11    0
Top12    0
Top13    0
Top14    0
Top15    0
Top16    0
Top17    0
Top18    0
Top19    0
Top20    0
Top21    0
Top22    0
Top23    0
Top24    0
Top25    0
dtype: int64


In [ ]:
# splitting train and test data
train = df[df['Date'] < '20150101']
test = df[df['Date'] > '20141231']


# removing punctuations
data=train.iloc[:,2:27]
data.replace("[^a-zA-Z]"," ",regex=True, inplace=True)
data1=test.iloc[:,2:27]
data1.replace("[^a-zA-Z]"," ",regex=True, inplace=True)



/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:5238: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(


In [ ]:


list1= [i for i in range(25)]
new_Index=[str(i) for i in list1]
data.columns= new_Index
data.head(5)
# Convertng headlines to lower case
for index in new_Index:
    data[index]=data[index].str.lower()

data.head(1)

headlines = []
for row in range(0,len(data.index)):

    headlines.append(' '.join(str(x) for x in data.iloc[row,0:25]))



<ipython-input-8-f4efab44752e>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[index]=data[index].str.lower()


In [ ]:
list2= [i for i in range(25)]
new_Index=[str(i) for i in list2]
data1.columns= new_Index
data1.head(5)
# Convertng headlines to lower case
for index in new_Index:
    data1[index]=data1[index].str.lower()


headlines1 = []
for row in range(0,len(data1.index)):

    headlines1.append(' '.join(str(x) for x in data1.iloc[row,0:25]))






<ipython-input-9-ea98fd7a9bdc>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1[index]=data1[index].str.lower()


In [ ]:
headlines
len(headlines)

3878

In [ ]:
w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
lemmatizer = nltk.stem.WordNetLemmatizer()
X=[]
#ps = PorterStemmer()
for x in headlines:
    #tokens=(word_tokenize(x))
    tokens=w_tokenizer.tokenize(x)
    lemma=[]
    for token in tokens:
     lemma_word=lemmatizer.lemmatize(token)
     #stemmed_word = ps.stem(token)
     lemma.append(lemma_word)
    X.append(lemma)
Y=[]
for j in X:
    Y.append(' '.join(j))
#print(Y[0])
Y

In [ ]:
Y
len(Y)

3878

In [ ]:
X1=[]
#ps = PorterStemmer()
for x in headlines1:
    #tokens=(word_tokenize(x))
    tokens=w_tokenizer.tokenize(x)
    lemma=[]
    for token in tokens:
     lemma_word=lemmatizer.lemmatize(token)
     #stemmed_word = ps.stem(token)
     lemma.append(lemma_word)
    X1.append(lemma)
Y1=[]
for j in X1:
    Y1.append(' '.join(j))
#print(Y[0])
Y1

In [ ]:




countvector=CountVectorizer(ngram_range=(2,2))
traindataset1=countvector.fit_transform(Y)
type(traindataset1)

scipy.sparse.csr.csr_matrix

In [ ]:
## implement BAG OF WORDS
tfidfvector=TfidfVectorizer(ngram_range=(2,2))
traindataset=tfidfvector.fit_transform(Y)



In [ ]:
naive=MultinomialNB()
naive.fit(traindataset,train['Label'])

test_transform= []
for row in range(0,len(test.index)):
    test_transform.append(' '.join(str(x) for x in test.iloc[row,2:27]))
test_dataset = tfidfvector.transform(Y1)
predictions1 = naive.predict(test_dataset)

predictions1

array(['1', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '1', '1',
       '1', '0', '1', '0', '0', '1', '0', '1', '1', '1', '1', '0', '0',
       '1', '0', '1', '1', '1', '0', '0', '1', '0', '1', '1', '0', '0',
       '1', '0', '0', '1', '0', '1', '0', '0', '1', '0', '1', '0', '1',
       '0', '1', '0', '0', '0', '0', '1', '1', '0', '0', '1', '1', '0',
       '1', '1', '1', '0', '1', '1', '0', '0', '1', '0', '1', '1', '1',
       '0', '1', '0', '0', '1', '1', '0', '0', '1', '1', '0', '0', '0',
       '1', '1', '1', '1', '0', '1', '0', '0', '1', '0', '0', '1', '0',
       '1', '0', '0', '0', '0', '1', '1', '0', '0', '1', '1', '1', '0',
       '1', '1', '0', '0', '1', '0', '1', '1', '0', '0', '1', '0', '1',
       '1', '1', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1',
       '1', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '1', '1',
       '1', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '1',
       '1', '0', '1', '0', '1', '1', '0', '1', '1', '0', '0', '1

In [ ]:
model = XGBClassifier()
model.fit(traindataset,train['Label'])
predictions2 = model.predict(test_dataset)
predictions2

array(['1', '0', '1', '1', '1', '0', '0', '0', '1', '1', '1', '1', '1',
       '1', '1', '1', '0', '0', '1', '1', '1', '1', '1', '1', '0', '0',
       '1', '1', '1', '1', '1', '1', '0', '1', '1', '1', '1', '0', '1',
       '1', '0', '0', '1', '0', '1', '0', '0', '1', '0', '1', '1', '1',
       '0', '1', '1', '0', '0', '0', '1', '1', '0', '0', '1', '1', '1',
       '1', '1', '1', '0', '1', '1', '1', '0', '1', '1', '1', '1', '1',
       '1', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1', '0',
       '1', '1', '1', '1', '0', '1', '0', '0', '1', '1', '0', '1', '0',
       '1', '0', '0', '0', '0', '1', '1', '0', '1', '1', '1', '1', '0',
       '1', '1', '1', '1', '1', '0', '1', '1', '0', '1', '1', '1', '1',
       '1', '1', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1',
       '1', '0', '1', '0', '0', '0', '0', '0', '1', '1', '0', '1', '1',
       '1', '0', '0', '0', '0', '0', '1', '1', '1', '0', '1', '1', '1',
       '0', '1', '1', '0', '1', '1', '1', '1', '1', '0', '0', '1

In [ ]:
# implement RandomForest Classifier
randomclassifier=RandomForestClassifier(n_estimators=200,criterion='entropy')
randomclassifier.fit(traindataset,train['Label'])

predictions3 = randomclassifier.predict(test_dataset)

In [ ]:
classifier = LogisticRegression(random_state = 0)
classifier.fit(traindataset,train['Label'])
predictions4=classifier.predict(test_dataset)
predictions4


array(['1', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '1', '1',
       '1', '0', '1', '0', '0', '1', '0', '1', '1', '1', '1', '0', '0',
       '1', '0', '1', '1', '1', '0', '0', '1', '0', '1', '1', '0', '0',
       '1', '0', '0', '1', '0', '1', '0', '0', '1', '0', '1', '0', '1',
       '0', '1', '0', '0', '0', '0', '1', '1', '0', '0', '1', '1', '0',
       '1', '1', '1', '0', '1', '1', '0', '0', '1', '0', '1', '1', '1',
       '0', '1', '0', '0', '1', '1', '0', '0', '1', '1', '0', '0', '0',
       '1', '1', '1', '1', '0', '1', '0', '0', '1', '0', '0', '1', '0',
       '1', '0', '0', '0', '0', '1', '1', '0', '0', '1', '1', '1', '0',
       '1', '1', '0', '0', '1', '0', '1', '1', '0', '0', '1', '0', '1',
       '1', '1', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1',
       '1', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '1', '1',
       '1', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '1',
       '1', '0', '1', '0', '1', '1', '0', '1', '1', '0', '0', '1

In [ ]:
# Using K-means
knn5 = KNeighborsClassifier(n_neighbors=5)
knn5.fit(traindataset,train['Label'])
predictions5= knn5.predict(test_dataset)



NameError: ignored

In [ ]:
#for naive bayes
matrix=confusion_matrix(test['Label'],predictions1)
print(matrix)
score=accuracy_score(test['Label'],predictions1)
print(score)
report=classification_report(test['Label'],predictions1)
print(report)


[[130  56]
 [  0 192]]
0.8518518518518519
              precision    recall  f1-score   support

           0       1.00      0.70      0.82       186
           1       0.77      1.00      0.87       192

    accuracy                           0.85       378
   macro avg       0.89      0.85      0.85       378
weighted avg       0.89      0.85      0.85       378



In [ ]:
# for xgboost
matrix=confusion_matrix(test['Label'],predictions2)
print(matrix)
score=accuracy_score(test['Label'],predictions2)
print(score)
report=classification_report(test['Label'],predictions2)
print(report)


[[109  77]
 [ 21 171]]
0.7407407407407407
              precision    recall  f1-score   support

           0       0.84      0.59      0.69       186
           1       0.69      0.89      0.78       192

    accuracy                           0.74       378
   macro avg       0.76      0.74      0.73       378
weighted avg       0.76      0.74      0.73       378



In [ ]:
# for random forest
matrix=confusion_matrix(test['Label'],predictions3)
print(matrix)
score=accuracy_score(test['Label'],predictions3)
print(score)
report=classification_report(test['Label'],predictions3)
print(report)


[[151  35]
 [ 20 172]]
0.8544973544973545
              precision    recall  f1-score   support

           0       0.88      0.81      0.85       186
           1       0.83      0.90      0.86       192

    accuracy                           0.85       378
   macro avg       0.86      0.85      0.85       378
weighted avg       0.86      0.85      0.85       378



In [ ]:
# for logistic regression
matrix=confusion_matrix(test['Label'],predictions4)
print(matrix)
score=accuracy_score(test['Label'],predictions4)
print(score)
report=classification_report(test['Label'],predictions4)
print(report)


[[132  54]
 [  0 192]]
0.8571428571428571
              precision    recall  f1-score   support

           0       1.00      0.71      0.83       186
           1       0.78      1.00      0.88       192

    accuracy                           0.86       378
   macro avg       0.89      0.85      0.85       378
weighted avg       0.89      0.86      0.85       378



In [ ]:
# for knn
matrix=confusion_matrix(test['Label'],predictions5)
print(matrix)
score=accuracy_score(test['Label'],predictions5)
print(score)
report=classification_report(test['Label'],predictions5)
print(report)


[[106  80]
 [ 58 134]]
0.6349206349206349
              precision    recall  f1-score   support

           0       0.65      0.57      0.61       186
           1       0.63      0.70      0.66       192

    accuracy                           0.63       378
   macro avg       0.64      0.63      0.63       378
weighted avg       0.64      0.63      0.63       378



In [ ]:
%%writefile app.py
import streamlit as st
st.title('Stock sentiment analysis')


Writing app.py


In [ ]:
if st.button('Predict'):
  st.header(predictions1)

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


NAME:
   ngrok - tunnel local ports to public URLs and inspect traffic

DESCRIPTION:
    ngrok exposes local networked services behinds NATs and firewalls to the
    public internet over a secure tunnel. Share local websites, build/test
    webhook consumers and self-host personal services.
    Detailed help for each command is available with 'ngrok help <command>'.
    Open http://localhost:4040 for ngrok's web interface to inspect traffic.

EXAMPLES:
    ngrok http 80                    # secure public URL for port 80 web server
    ngrok http -subdomain=baz 8080   # port 8080 available at baz.ngrok.io
    ngrok http foo.dev:80            # tunnel to host:port instead of localhost
    ngrok http https://localhost     # expose a local https server
    ngrok tcp 22                     # tunnel arbitrary TCP traffic to port 22
    ngrok tls -hostname=foo.com 443  # TLS traffic for foo.com to port 443
    ngrok start foo bar baz          # start tunnels from the configuration file

VERSI

In [ ]:
#from pyngrok import ngrok

In [ ]:
!streamlit run app.py & npx localtunnel --port 8501
#! nohup streamlit run app.py &

[..................] \ fetchMetadata: sill resolveWithNewModule localtunnel@2.0


  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.12:8502
  External URL: http://104.196.137.191:8502

npx: installed 22 in 4.576s
your url is: https://silent-bats-cheer-104-196-137-191.loca.lt


In [ ]:
#!pgrep streamlit

731
806


In [ ]:
#url = ngrok.connect(port='8501')

INFO:pyngrok.ngrok:Opening tunnel named: http-80-1ec2ce2b-3ab1-46db-9408-c4de441cd688
2022-12-04 17:06:10.990 INFO    pyngrok.ngrok: Opening tunnel named: http-80-1ec2ce2b-3ab1-46db-9408-c4de441cd688
INFO:pyngrok.process.ngrok:t=2022-12-04T17:06:11+0000 lvl=info msg="no configuration paths supplied"
2022-12-04 17:06:11.067 INFO    pyngrok.process.ngrok: t=2022-12-04T17:06:11+0000 lvl=info msg="no configuration paths supplied"
INFO:pyngrok.process.ngrok:t=2022-12-04T17:06:11+0000 lvl=info msg="using configuration at default config path" path=/root/.ngrok2/ngrok.yml
2022-12-04 17:06:11.074 INFO    pyngrok.process.ngrok: t=2022-12-04T17:06:11+0000 lvl=info msg="using configuration at default config path" path=/root/.ngrok2/ngrok.yml
INFO:pyngrok.process.ngrok:t=2022-12-04T17:06:11+0000 lvl=info msg="open config file" path=/root/.ngrok2/ngrok.yml err=nil
2022-12-04 17:06:11.078 INFO    pyngrok.process.ngrok: t=2022-12-04T17:06:11+0000 lvl=info msg="open config file" path=/root/.ngrok2/ngro

In [ ]:
#print(url)

NgrokTunnel: "http://8b32-104-196-137-191.ngrok.io" -> "http://localhost:80"


In [ ]:
!streamlit run STOCK_SHARE_PREDICTOR.ipy

Usage: streamlit run [OPTIONS] TARGET [ARGS]...

Error: Streamlit requires raw Python (.py) files, not .ipynb.
For more information, please see https://docs.streamlit.io


# New section